// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  /**
   * Resend API key used to send transactional emails.
   * Configure this in your Cloudflare Pages project settings.
   */
  RESEND_API_KEY: string;

  /**
   * The email address that should receive messages
   * from the portfolio contact form.
   */
  CONTACT_RECIPIENT_EMAIL: string;
}
